apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: faraohh/conversao-temperatura:latest
      ports:
        - containerPort: 8080

---
#
apiVersion: v1
kind: Pod
metadata:
  name: meupod-label
  labels:
    app: web
spec:
  containers:
    - name: web
      image: faraohh/conversao-temperatura:latest
      ports:
        - containerPort: 8080
